# Generated by Django 3.2.9 on 2021-11-06 19:36

from django.db import migrations
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniregister',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
            preserve_default=False,
        ),
    ]
