# Generated by Django 3.2.2 on 2021-11-23 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0003_auto_20211106_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniregister',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
