# Generated by Django 3.2.2 on 2021-11-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0006_auto_20211123_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(),
        ),
    ]
