# Generated by Django 3.2.2 on 2021-11-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0007_alter_event_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.CharField(max_length=30),
        ),
    ]
