# Generated by Django 3.2.6 on 2022-01-04 04:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0008_alter_event_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniregister',
            name='course_graduated',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumniregister',
            name='currently_connected_to',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumniregister',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=30),
        ),
        migrations.AddField(
            model_name='alumniregister',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='alumniregister',
            name='passout_batch',
            field=models.IntegerField(default=2012),
            preserve_default=False,
        ),
    ]
