# Generated by Django 3.2.6 on 2022-01-04 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0009_auto_20220104_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniregister',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
