# Generated by Django 3.2.6 on 2022-01-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_chat_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
