# Generated by Django 3.2.6 on 2022-01-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_chat_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregister',
            name='batch',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentregister',
            name='course',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentregister',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='iamge'),
        ),
        migrations.AddField(
            model_name='studentregister',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resume'),
        ),
        migrations.AddField(
            model_name='studentregister',
            name='semester',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
